# this is travis script for testing uLaunchELF compilation and automatic
# upload in releases if branch is tagged
deploy:
  provider: releases
  api_key: $APIKEY
  file: uLaunchelf_$TRAVIS_COMMIT.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

sudo: required

install:
 ## Dependencies
- sudo apt-get install -yqqq gcc-4.4 patch wget make git libc6-dev zlib1g zlib1g-dev libucl1 libucl-dev
 ## ps2dev

before_script:
# setting environment
- export PS2DEV=${HOME}/ps2dev
- export PS2SDK=${PS2DEV}/ps2sdk
- export PATH=${PATH}:${PS2DEV}/bin:${PS2DEV}/ee/bin:${PS2DEV}/iop/bin:${PS2DEV}/dvp/bin:${PS2SDK}/bin
# installing ps2toolchain (without ps2sdk and ps2link)
- git clone https://github.com/ps2dev/ps2toolchain.git
- cd ps2toolchain/
# scripts are silenced cause log will be enormous if we will see all output from toolchain setup
- bash ./toolchain.sh 1 > /tmp/PS2TOOLCHAIN1.log 2>&1
- bash ./toolchain.sh 2 > /tmp/PS2TOOLCHAIN2.log 2>&1
- bash ./toolchain.sh 3 > /tmp/PS2TOOLCHAIN3.log 2>&1
- bash ./toolchain.sh 4 > /tmp/PS2TOOLCHAIN4.log 2>&1
- cd $TRAVIS_BUILD_DIR
# installing ps2sdk at specific commit
- git clone https://github.com/ps2dev/ps2sdk.git
- cd ps2sdk
#- git checkout 9d1d184
- make -j2 install --silent
- cd $TRAVIS_BUILD_DIR
# installing ps2eth
- git clone https://github.com/ps2dev/ps2eth.git
- cd ps2eth
- make
- mkdir -p $PS2DEV/ps2eth
- tar c `find . -name \*irx` | tar x -C $PS2DEV/ps2eth
- cd $TRAVIS_BUILD_DIR
# installing libjpeg
- git clone https://github.com/ps2dev/ps2sdk-ports.git
- cd ps2sdk-ports/libjpeg
- make install
- cd $TRAVIS_BUILD_DIR
# installing gsKit
- export GSKIT=${PS2DEV}/gsKit
- git clone https://github.com/ps2dev/gsKit.git
- cd gsKit/
- bash ./setup.sh
- cd $TRAVIS_BUILD_DIR
# installing ps2-packer
- git clone https://github.com/ps2dev/ps2-packer.git
- cd ps2-packer
- make install

script:
- cd $TRAVIS_BUILD_DIR
- make
- zip uLaunchelf_$TRAVIS_COMMIT.zip ULE.ELF
- curl --upload-file uLaunchelf_$TRAVIS_COMMIT.zip https://transfer.sh/uLaunchelf.zip | grep transfer
